// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ContentItem: typeof import('./src/components/home/ContentItem.vue')['default']
    ContentLeftItem: typeof import('./src/components/home/ContentLeftItem.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    Footer: typeof import('./src/components/home/Footer.vue')['default']
    Header: typeof import('./src/components/home/Header.vue')['default']
    HeroHome: typeof import('./src/components/home/HeroHome.vue')['default']
    Home: typeof import('./src/views/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SloganLeftItem: typeof import('./src/components/home/SloganLeftItem.vue')['default']
    SloganRightItem: typeof import('./src/components/home/SloganRightItem.vue')['default']
    SloganTopItem: typeof import('./src/components/home/SloganTopItem.vue')['default']
  }
}
